#!/bin/bash

echo "Check with device disconnected"
echo "Press ENTER to proceed"
read

ls /dev/tty* > dev1.txt

echo "Check with device connected"
echo "Connect the device and press ENTER to proceed"
read

ls /dev/tty* > dev2.txt

echo "Device connected to:"
diff dev1.txt dev2.txt

rm dev1.txt dev2.txt
